### PR TITLE
fix: Parsing of options to Clappr

### LINKED ISSUE #58: [q] How do you implement clappr plugins?
How do you implement clappr plugins that use jquery?

### PR DESCRIPTION
**Pull request by genofire**
should solve the usage of unknown options e.g. from a plugin

fixed #58

---

it is untested ....
now, tested local and it works ;)

### CODE REVIEW

**Comment by genofire** [comment]
@vinayakkulkarni any update ?

**Comment by vinayakkulkarni** [comment]
> @vinayakkulkarni any update ?

Will review over the weekend.

**Comment by genofire** [comment]
and a rebase again -> @vinayakkulkarni any update after a month of your last message?

**Comment by vinayakkulkarni** [comment]
Hey,

Sorry I'm a bit preoccupied cause my parents are admitted in ICU due to COVID-19.

Will check and revert soon.

--
Regards,
Vinayak Kulkarni.

Sent via Spark Mail

**Comment by genofire** [comment]
Hope your parents get well.

**Comment by vinayakkulkarni** [comment]
Already refactored v2.x to make use of `options` sent by user.

**Comment by genofire** [comment]
Thank you, hope you and your family get well.

**Comment by vinayakkulkarni** [comment]
> Thank you, hope you and your family get well.
> 
> I will try the new Version

My mom and dad passed away due to COVID.

I've updated the docs with the demo to codesandbox, you can fork and try that.

**Pull request closed without merging**
